### ISSUE TITLE
Carry over more metadata for certain launchers

### ISSUE THREAD

**Issue by KTrain5169** [Polyfrost/OneLauncher#233]
### Is your suggested enhancement related to a problem? Please describe, or link another Issue.

I noticed that some metadata that could be carried over from other launchers aren't. While this isn't the most groundbreaking thing it would be nice to have them carry over.

Example: MultiMC/Prism's time played, so I can see ~~how addicted I was to playing~~ how much playtime I have

### Describe the solution you'd like

Just an extra option that says "Import instance metadata as well" or something.

### Describe alternatives you've considered

I thought about doing it automatically without a checkbox but some people might not want that data to be carried over.

**Comment by Wyvest** [comment]
report this to discord instead of here
